unbind C-b
set -g prefix C-a

set-window-option -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r H resize-pane -L 5
bind-key -r L resize-pane -R 5

# tmux-yank
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# switch mouse support on
set -g mouse on

# use vi keyboard shortcuts in copy mode
setw -g mode-keys vi

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# automatically restore tmux environment when tmux is started
set -g @continuum-restore 'on'
set -g @continuum-boot-options 'iterm'

# List of plugins
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'xamut/tmux-weather'
set -g @catppuccin_flavour 'mocha' # or frappe, macchiato, mocha
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_current_text " #{b:pane_current_path}"
set -g @catppuccin_window_text " #{b:pane_current_path}"
set -g @cpu_percentage_format "%2.0f%%" # printf format to use to display percentage
set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_weather}"
set -agF status-right "#{E:@catppuccin_status_battery}"

set -g @resurrect-strategy-vim 'session' # to resurrect vim

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
 # NOTE: prefix + U to update tmux plugins
run '~/.tmux/plugins/tpm/tpm'
