# Here you list all the shortcuts. To reload, turn the extension off and on.
#
# The shortcuts may be defined in two ways:
#
# 1. Run-or-raise form: shortcut,command,[wm_class],[title]
#        * `wm_class` and `title` are optional and case sensitive
#        * if none is set, lowercased launch `command` is compared with lowercased windows wm_classes and titles
#
# 2. Run only form: shortcut,command
#
#
# In fact, the full form is `shortcut[ char][:mode],command,[wm_class],[title]`
# while `char` allows you to use layered shortcuts and `mode` to further specify circumstances.
#
# =================
# Run or raise form
# =================
# see https://github.com/CZ-NIC/run-or-raise?tab=readme-ov-file#understanding-title-and-wm_class
<Super>g,ghostty,,
<Super>b,com.google.Chrome.desktop,,

# =============
# Run only form
# =============
#
# This line will launch the `notify-send` command.
<Super>y,notify-send Hello world
