onboarding = false

[keys]
prefix = "ctrl+space"

[theme]
auto_switch = true
dark_name = "tokyo-night"
light_name = "rose-pine-dawn"

[ui.toast]
delivery = "herdr"

[ui.sound]
enabled = true

[ui]
status_indicators = "symbols"
show_agent_labels_on_pane_borders = true
agent_panel_sort = "spaces"
hide_tab_bar_when_single_tab = true
